version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: db
      DATABASE_USER: imdb_user
      DATABASE_PASSWORD: imdb_pass
      DATABASE_NAME: imdb_db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: imdb_user
      POSTGRES_PASSWORD: imdb_pass
      POSTGRES_DB: imdb_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
      - ./raw_data:/raw_data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U imdb_user -d imdb_db"]
      interval: 10s
      timeout: 5s
      retries: 5      
volumes:
  postgres_data: